// status: "planned" | "shot" | "cut" | "final"
// When a design is built, set status, date, path, and fill in `result` and `ledTo`.
const PHASES = {
  1: { title: "Broad strokes", blurb: "Wildly different territories. What even works for a café?" },
  2: { title: "Going deeper", blurb: "Push the most interesting directions further, then combine what worked. Some die here." },
  3: { title: "Final three", blurb: "The best three, refined, with reasons." }
};

const ENTRIES = [
  { n: 1, status: "shot", date: "2026-10-04", path: "designs/01-film-script/index.html",  phase: 1, title: "Film Script", tag: "Structure", hue: 40,
    question: "Can a whole landing page read as a screenplay without becoming unreadable?",
    idea: "INT. THE CAFÉ - DAY. Menu items as scene descriptions, Courier, proper script margins." },
  { n: 2, status: "shot", date: "2026-10-04", path: "designs/02-end-credits/index.html",  phase: 1, title: "End Credits Roll", tag: "Structure", hue: 0,
    question: "What if the menu is the credits, and scrolling is the only interaction?",
    idea: "Black field, white type, centered roles and names. Hover pauses the roll." },
  { n: 3, status: "shot", date: "2026-10-05", path: "designs/03-cinema-marquee/index.html", phase: 1, title: "Cinema Marquee", tag: "Physical", hue: 50,
    question: "How far can one physical object carry a whole hero section?",
    idea: "A letter-board marquee with changeable, animated letters." },
  { n: 4, status: "shot", date: "2026-10-05", path: "designs/04-letterboxed/index.html", phase: 1, title: "Letterboxed", tag: "Frame", hue: 220,
    question: "Does constraining everything to 2.39:1 feel cinematic or just cramped?",
    idea: "Black bars top and bottom; copy appears as subtitles." },
  { n: 5, status: "shot", date: "2026-10-05", path: "designs/05-storyboard/index.html", phase: 1, title: "Storyboard", tag: "Structure", hue: 30,
    question: "Can the page tell the café's story in panels, with sketchy hand-drawn CSS?",
    idea: "Numbered panels with camera notes: what it is, the menu, come in." },
  { n: 6, status: "shot", date: "2026-10-05", path: "designs/06-seating-chart/index.html", phase: 1, title: "Seating Chart", tag: "Interaction", hue: 350,
    question: "Is booking-a-seat UI a better landing page than a hero?",
    idea: "Tables are seats. Pick a seat, see that genre's menu." },
  { n: 7, status: "shot", date: "2026-10-05", path: "designs/07-vhs-tape/index.html", phase: 1, title: "VHS Tape", tag: "Era", hue: 280,
    question: "How much glitch is charming before it hurts legibility?",
    idea: "Scanlines, tracking errors, burned-in timestamp, glitch on interaction." },
  { n: 8, status: "shot", date: "2026-10-05", path: "designs/08-film-negative/index.html", phase: 1, title: "Film Negative", tag: "Medium", hue: 190,
    question: "What changes when the whole palette is inverted?",
    idea: "Inverted tones; menu items are exposures on a strip." },

  { n: 9, status: "shot", date: "2026-10-05", path: "designs/09-silent-film/index.html", phase: 2, title: "Silent Film", tag: "Era", hue: 35,
    question: "Can intertitle cards replace sections entirely?",
    idea: "Tinted cards, iris transitions, no hero image." },
  { n: 10, status: "shot", date: "2026-10-05", path: "designs/10-lobby-card/index.html", phase: 2, title: "Lobby Card", tag: "Illustration", hue: 15,
    question: "Can CSS alone fake 1940s hand-lettered poster art?",
    idea: "Illustrated, saturated, borders and starbursts." },
  { n: 11, status: "shot", date: "2026-10-05", path: "designs/11-cable-access/index.html", phase: 2, title: "Cable Access, 1987", tag: "Era", hue: 160,
    question: "Is earnest low-budget TV funnier and warmer than polished?",
    idea: "Test patterns, static, lower-third graphics, a phone number." },
  { n: 12, status: "shot", date: "2026-10-05", path: "designs/12-all-type/index.html", phase: 2, title: "All-Type Brutalist", tag: "Typography", hue: 60,
    question: "How loud can type be with zero images?",
    idea: "Enormous menu type, harsh grid, color blocks." },
  { n: 13, status: "shot", date: "2026-10-05", path: "designs/13-title-sequence/index.html", phase: 2, title: "Title Sequence", tag: "Motion", hue: 0,
    question: "Can a Saul Bass-style opening be the landing page?",
    idea: "Type animates in on a timer or scroll, then settles." },
  { n: 14, status: "shot", date: "2026-10-05", path: "designs/14-type-morph/index.html", phase: 2, title: "Variable Type Morph", tag: "Typography", hue: 300,
    question: "Can one word carry the whole mood by changing shape?",
    idea: "A single word morphing between emotional states, no variable font file needed." },
  { n: 15, status: "shot", date: "2026-10-05", path: "designs/15-genre-switcher/index.html", phase: 2, title: "Genre Switcher", tag: "Interaction", hue: 120,
    question: "Does one content set survive eight radically different skins?",
    idea: "Pick a genre; the entire aesthetic transforms." },
  { n: 16, status: "shot", date: "2026-10-05", path: "designs/16-terminal/index.html", phase: 2, title: "Terminal", tag: "Interaction", hue: 130,
    question: "Is typing an order more fun than clicking one?",
    idea: "Command-line UI, keyboard-driven menu browsing." },

  { n: 17, status: "shot", date: "2026-10-05", path: "designs/17-directors-commentary/index.html", phase: 2, title: "Director's Commentary", tag: "Interaction", hue: 25,
    question: "Can hover annotations make a page feel like a DVD extra?",
    idea: "Hover any element for a commentary-track note." },
  { n: 18, status: "shot", date: "2026-10-05", path: "designs/18-choose-your-screening/index.html", phase: 2, title: "Choose Your Screening", tag: "Narrative", hue: 260,
    question: "Does branching make a landing page memorable or annoying?",
    idea: "Dark or light? Each answer routes to a different version." },
  { n: 19, status: "shot", date: "2026-10-05", path: "designs/19-display-case/index.html", phase: 2, title: "Lobby Display Case", tag: "Physical", hue: 45,
    question: "Can parallax depth sell a glass case?",
    idea: "Lit cabinets outside a cinema; menu items sit inside." },
  { n: 20, status: "shot", date: "2026-10-05", path: "designs/20-menu-board/index.html", phase: 2, title: "Overhead Menu Board", tag: "Physical", hue: 90,
    question: "Is the backlit counter board a better menu than a grid?",
    idea: "White letters on black tracks; click a row to expand." },
  { n: 21, status: "shot", date: "2026-10-05", path: "designs/21-storyboard-in-color/index.html", phase: 3, title: "Storyboard in Color", tag: "Hybrid", hue: 20,
    question: "What happens when the storyboard look of 05 takes the genre colors and patterns of 15 and the story lines of 09?",
    idea: "Eight shots, one per genre: pencil sketches on a patterned color wash, a line of story under each, and panels taped to the sheet." },
  { n: 22, status: "shot", date: "2026-10-05", path: "designs/22-cafe-storyboard/index.html", phase: 3, title: "Café Storyboard", tag: "Hybrid", hue: 200,
    question: "Does the storyboard from 21 read as a café once it has a home page, an about section and a visit section around the menu?",
    idea: "21 plus a sticky About, Menu and Visit bar, a hero with a café-front sketch, an about section, the eight genre panels as the menu, and a visit section with address and hours." },

  { n: 23, status: "shot", date: "2026-10-05", path: "designs/23-pop-art-cafe/index.html", phase: 3, title: "Pop Art Café", tag: "Hybrid", hue: 330,
    question: "Keep the full café site of 22 but swap the pencil storyboard for the bright pop art of the lobby cards (10) and the cable guide (11). Does the louder look still read clearly as a café?",
    idea: "The same About, Menu and Visit us structure with halftone dots, thick outlines, hard shadows, starbursts and lobby-card style genre cards that show every drink and price, with descriptions in a pop-up." },
  { n: 24, phase: 3, title: "Streaming Service", tag: "Concept", hue: 340,
    question: "Is parodying the streaming UI too familiar to be unique?",
    idea: "'Recommended for you: The Bitter Espresso (2024, Noir, 4 stars).'" },
  { n: 25, phase: 3, title: "The 404", tag: "Concept", hue: 5,
    question: "Can an error page be the most inviting page?",
    idea: "'We couldn't find what you were looking for. We found something better.'" }
].map(e => ({ status: "planned", date: null, path: null, result: null, ledTo: null, ...e }));
