// status: "planned" | "shot" | "cut" | "final"
// When a design is built, set status, date, path, and fill in `result` and `ledTo`.
const ENTRIES = [
  { n: 1, desc: "The whole café written as a screenplay: a title page, scene headings for each genre, and drinks set like characters.", status: "shot", date: "2026-10-04", path: "designs/01-film-script/index.html",  phase: 1, title: "Film Script", tag: "Structure", hue: 40,
    question: "Can a whole landing page read as a screenplay without becoming unreadable?",
    idea: "INT. THE CAFÉ - DAY. Menu items as scene descriptions, Courier, proper script margins." },
  { n: 2, desc: "The menu scrolls like film credits over a grainy projector beam, with each genre as its own credit unit.", status: "shot", date: "2026-10-04", path: "designs/02-end-credits/index.html",  phase: 1, title: "End Credits Roll", tag: "Structure", hue: 0,
    question: "What if the menu is the credits, and scrolling is the only interaction?",
    idea: "Black field, white type, centered roles and names. Hover pauses the roll." },
  { n: 3, desc: "A glowing cinema marquee with a flipping letter board. Pick a genre ticket and the sign changes.", status: "shot", date: "2026-10-05", path: "designs/03-cinema-marquee/index.html", phase: 1, title: "Cinema Marquee", tag: "Physical", hue: 50,
    question: "How far can one physical object carry a whole hero section?",
    idea: "A letter-board marquee with changeable, animated letters." },
  { n: 4, desc: "A widescreen short film where scrolling plays one painted scene per genre and the drinks appear as subtitles.", status: "shot", date: "2026-10-05", path: "designs/04-letterboxed/index.html", phase: 1, title: "Letterboxed", tag: "Frame", hue: 220,
    question: "Does constraining everything to 2.39:1 feel cinematic or just cramped?",
    idea: "Black bars top and bottom; copy appears as subtitles." },
  { n: 5, desc: "The café drawn as pencil storyboard panels, one shot per genre, with jump links across the top.", status: "shot", date: "2026-10-05", path: "designs/05-storyboard/index.html", phase: 1, title: "Storyboard", tag: "Structure", hue: 30,
    question: "Can the page tell the café's story in panels, with sketchy hand-drawn CSS?",
    idea: "Numbered panels with camera notes: what it is, the menu, come in." },
  { n: 6, desc: "Choose drinks like cinema seats. The screen previews each one and a ticket list adds up your picks.", status: "shot", date: "2026-10-05", path: "designs/06-seating-chart/index.html", phase: 1, title: "Seating Chart", tag: "Interaction", hue: 350,
    question: "Is booking-a-seat UI a better landing page than a hero?",
    idea: "Tables are seats. Pick a seat, see that genre's menu." },
  { n: 7, desc: "A 1980s video store where every genre is a tape you flip over to read the menu on the back of the box.", status: "shot", date: "2026-10-05", path: "designs/07-vhs-tape/index.html", phase: 1, title: "VHS Tape", tag: "Era", hue: 280,
    question: "How much glitch is charming before it hurts legibility?",
    idea: "Scanlines, tracking errors, burned-in timestamp, glitch on interaction." },
  { n: 8, desc: "Film strips on a light table. Hover over a frame to develop the negative into a drawing of the drink.", status: "shot", date: "2026-10-05", path: "designs/08-film-negative/index.html", phase: 1, title: "Film Negative", tag: "Medium", hue: 190,
    question: "What changes when the whole palette is inverted?",
    idea: "Inverted tones; menu items are exposures on a strip." },

  { n: 9, desc: "A silent picture told in gold intertitle cards, stepped with the arrow keys and a reel index along the bottom.", status: "shot", date: "2026-10-05", path: "designs/09-silent-film/index.html", phase: 2, title: "Silent Film", tag: "Era", hue: 35,
    question: "Can intertitle cards replace sections entirely?",
    idea: "Tinted cards, iris transitions, no hero image." },
  { n: 10, desc: "Eight pinned lobby cards, one per genre. Pull a card out to see its drinks.", status: "shot", date: "2026-10-05", path: "designs/10-lobby-card/index.html", phase: 2, title: "Lobby Card", tag: "Illustration", hue: 15,
    question: "Can CSS alone fake 1940s hand-lettered poster art?",
    idea: "Illustrated, saturated, borders and starbursts." },
  { n: 11, desc: "A 1987 community channel guide: genres are channels, drinks are programs, and each opens a description card.", status: "shot", date: "2026-10-05", path: "designs/11-cable-access/index.html", phase: 2, title: "Cable Access, 1987", tag: "Era", hue: 160,
    question: "Is earnest low-budget TV funnier and warmer than polished?",
    idea: "Test patterns, static, lower-third graphics, a phone number." },
  { n: 12, desc: "A type-only menu in ruled tables, with buttons to sort by genre, by price or A to Z.", status: "shot", date: "2026-10-05", path: "designs/12-all-type/index.html", phase: 2, title: "All-Type Brutalist", tag: "Typography", hue: 60,
    question: "How loud can type be with zero images?",
    idea: "Enormous menu type, harsh grid, color blocks." },
  { n: 13, desc: "A cut-paper film title sequence that settles into a poster, with a button for each genre.", status: "shot", date: "2026-10-05", path: "designs/13-title-sequence/index.html", phase: 2, title: "Title Sequence", tag: "Motion", hue: 0,
    question: "Can a Saul Bass-style opening be the landing page?",
    idea: "Type animates in on a timer or scroll, then settles." },
  { n: 14, desc: "One word that changes shape as you turn a genre dial, with that genre's menu beneath it.", status: "shot", date: "2026-10-05", path: "designs/14-type-morph/index.html", phase: 2, title: "Variable Type Morph", tag: "Typography", hue: 300,
    question: "Can one word carry the whole mood by changing shape?",
    idea: "A single word morphing between emotional states, no variable font file needed." },
  { n: 15, desc: "One page, eight looks. Pick a genre and the whole café restyles itself.", status: "shot", date: "2026-10-05", path: "designs/15-genre-switcher/index.html", phase: 2, title: "Genre Switcher", tag: "Interaction", hue: 120,
    question: "Does one content set survive eight radically different skins?",
    idea: "Pick a genre; the entire aesthetic transforms." },
  { n: 16, desc: "A café you order from by typing commands or clicking suggestions, with a running ticket.", status: "shot", date: "2026-10-05", path: "designs/16-terminal/index.html", phase: 2, title: "Terminal", tag: "Interaction", hue: 130,
    question: "Is typing an order more fun than clicking one?",
    idea: "Command-line UI, keyboard-driven menu browsing." },

  { n: 17, desc: "A gold DVD menu with a commentary switch that reveals the director's note on each drink.", status: "shot", date: "2026-10-05", path: "designs/17-directors-commentary/index.html", phase: 2, title: "Director's Commentary", tag: "Interaction", hue: 25,
    question: "Can hover annotations make a page feel like a DVD extra?",
    idea: "Hover any element for a commentary-track note." },
  { n: 18, desc: "A choose-your-own-adventure: two doors and a few questions lead you to a genre and its drinks.", status: "shot", date: "2026-10-05", path: "designs/18-choose-your-screening/index.html", phase: 2, title: "Choose Your Screening", tag: "Narrative", hue: 260,
    question: "Does branching make a landing page memorable or annoying?",
    idea: "Dark or light? Each answer routes to a different version." },
  { n: 19, desc: "A lit glass display case with a shelf for every genre, shifting in depth as you move across it.", status: "shot", date: "2026-10-05", path: "designs/19-display-case/index.html", phase: 2, title: "Lobby Display Case", tag: "Physical", hue: 45,
    question: "Can parallax depth sell a glass case?",
    idea: "Lit cabinets outside a cinema; menu items sit inside." },
  { n: 20, desc: "Backlit menu panels hung over a counter, with a bell that picks a random drink for you.", status: "shot", date: "2026-10-05", path: "designs/20-menu-board/index.html", phase: 2, title: "Overhead Menu Board", tag: "Physical", hue: 90,
    question: "Is the backlit counter board a better menu than a grid?",
    idea: "White letters on black tracks; click a row to expand." },
  { n: 21, desc: "The storyboard of design 5 in color, with a pattern and palette for each genre and a line of story on every panel.", status: "shot", date: "2026-10-05", path: "designs/21-storyboard-in-color/index.html", phase: 3, title: "Storyboard in Color", tag: "Hybrid", hue: 20,
    question: "What happens when the storyboard look of 05 takes the genre colors and patterns of 15 and the story lines of 09?",
    idea: "Eight shots, one per genre: pencil sketches on a patterned color wash, a line of story under each, and panels taped to the sheet." },
  { n: 22, desc: "A full café site in the storyboard style, with a home section, About us, the menu and Visit us.", status: "shot", date: "2026-10-05", path: "designs/22-cafe-storyboard/index.html", phase: 3, title: "Café Storyboard", tag: "Hybrid", hue: 200,
    question: "Does the storyboard from 21 read as a café once it has a home page, an about section and a visit section around the menu?",
    idea: "21 plus a sticky About, Menu and Visit bar, a hero with a café-front sketch, an about section, the eight genre panels as the menu, and a visit section with address and hours." },

  { n: 23, desc: "The same full café site in bright pop art, with starbursts and lobby-card style genre cards.", status: "shot", date: "2026-10-05", path: "designs/23-pop-art-cafe/index.html", phase: 3, title: "Pop Art Café", tag: "Hybrid", hue: 330,
    question: "Keep the full café site of 22 but swap the pencil storyboard for the bright pop art of the lobby cards (10) and the cable guide (11). Does the louder look still read clearly as a café?",
    idea: "The same About, Menu and Visit us structure with halftone dots, thick outlines, hard shadows, starbursts and lobby-card style genre cards that show every drink and price, with descriptions in a pop-up." },
  { n: 24, desc: "A café site built like a film's DVD: a main menu, a card-by-card menu and an end-credits Visit us.", status: "shot", date: "2026-10-05", path: "designs/24-feature-presentation/index.html", phase: 3, title: "Feature Presentation", tag: "Hybrid", hue: 345,
    question: "Can the credits roll of 02, the card-by-card silent picture of 09 and the DVD menu of 17 become one cinematic café site with the full café information?",
    idea: "A DVD main menu leads to About us as an intertitle card, the menu as eight chapter cards stepped with arrow keys and director's notes, and Visit us as the end credits roll." },
  { n: 25, desc: "A cinema-café front: a marquee with ticket buttons, the menu in a glass display case, and a counter with a bell.", status: "shot", date: "2026-10-05", path: "designs/25-theater-front/index.html", phase: 3, title: "Theater Front", tag: "Hybrid", hue: 8,
    question: "Can the marquee of 03, the display case of 19 and the backlit counter of 20 become one cinema-café front, with the full café information?",
    idea: "A lit marquee with a flipping letter board and ticket buttons, an About us poster case, the menu as a glass display case with parallax, and a Visit us counter scene with backlit panels and a bell that picks a random drink." }
].map(e => ({ status: "planned", date: null, path: null, result: null, ledTo: null, ...e }));
